/* Sonobi - Morpheus version: 3.22.3 */
(function(){var w="function"==typeof Object.defineProperties?Object.defineProperty:function(k,c,d){k!=Array.prototype&&k!=Object.prototype&&(k[c]=d.value)},x="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function z(){z=function(){};x.Symbol||(x.Symbol=E)}var H=0;function E(k){return"jscomp_symbol_"+(k||"")+H++}
function I(){z();var k=x.Symbol.iterator;k||(k=x.Symbol.iterator=x.Symbol("iterator"));"function"!=typeof Array.prototype[k]&&w(Array.prototype,k,{configurable:!0,writable:!0,value:function(){return K(this)}});I=function(){}}function K(k){var c=0;return L(function(){return c<k.length?{done:!1,value:k[c++]}:{done:!0}})}function L(k){I();k={next:k};k[x.Symbol.iterator]=function(){return this};return k}function M(k){I();z();I();var c=k[Symbol.iterator];return c?c.call(k):K(k)}
function N(k){for(var c,d=[];!(c=k.next()).done;)d.push(c.value);return d}function O(k){return k instanceof Array?k:N(M(k))}function P(k,c){if(c){var d=x;k=k.split(".");for(var a=0;a<k.length-1;a++){var n=k[a];n in d||(d[n]={});d=d[n]}k=k[k.length-1];a=d[k];c=c(a);c!=a&&null!=c&&w(d,k,{configurable:!0,writable:!0,value:c})}}
P("Promise",function(k){function c(a){this.D=0;this.M=void 0;this.C=[];var m=this.G();try{a(m.resolve,m.reject)}catch(h){m.reject(h)}}function d(){this.C=null}function a(a){return a instanceof c?a:new c(function(m){m(a)})}if(k)return k;d.prototype.D=function(a){this.C||(this.C=[],this.K());this.C.push(a)};d.prototype.K=function(){var a=this;this.G(function(){a.N()})};var n=x.setTimeout;d.prototype.G=function(a){n(a,0)};d.prototype.N=function(){for(;this.C&&this.C.length;){var a=this.C;this.C=[];for(var c=
0;c<a.length;++c){var h=a[c];delete a[c];try{h()}catch(g){this.M(g)}}}this.C=null};d.prototype.M=function(a){this.G(function(){throw a;})};c.prototype.G=function(){function a(a){return function(b){h||(h=!0,a.call(c,b))}}var c=this,h=!1;return{resolve:a(this.ta),reject:a(this.K)}};c.prototype.ta=function(a){if(a===this)this.K(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.Da(a);else{a:switch(typeof a){case "object":var l=null!=a;break a;case "function":l=!0;break a;
default:l=!1}l?this.sa(a):this.N(a)}};c.prototype.sa=function(a){var c=void 0;try{c=a.then}catch(h){this.K(h);return}"function"==typeof c?this.Ea(c,a):this.N(a)};c.prototype.K=function(a){this.V(2,a)};c.prototype.N=function(a){this.V(1,a)};c.prototype.V=function(a,c){if(0!=this.D)throw Error("Cannot settle("+a+", "+c|"): Promise already settled in state"+this.D);this.D=a;this.M=c;this.ha()};c.prototype.ha=function(){if(this.C){for(var a=this.C,c=0;c<a.length;++c)a[c].call(),a[c]=null;this.C=null}};
var l=new d;c.prototype.Da=function(a){var c=this.G();a.Ga(c.resolve,c.reject)};c.prototype.Ea=function(a,c){var h=this.G();try{a.call(c,h.resolve,h.reject)}catch(g){h.reject(g)}};c.prototype.then=function(a,l){function h(a,e){return"function"==typeof a?function(e){try{g(a(e))}catch(r){b(r)}}:e}var g,b,e=new c(function(a,e){g=a;b=e});this.Ga(h(a,g),h(l,b));return e};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.Ga=function(a,c){function h(){switch(g.D){case 1:a(g.M);break;
case 2:c(g.M);break;default:throw Error("Unexpected state: "+g.D);}}var g=this;this.C?this.C.push(function(){l.D(h)}):l.D(h)};c.resolve=a;c.reject=function(a){return new c(function(c,h){h(a)})};c.race=function(l){return new c(function(c,h){for(var g=M(l),b=g.next();!b.done;b=g.next())a(b.value).Ga(c,h)})};c.all=function(l){var d=M(l),h=d.next();return h.done?a([]):new c(function(g,b){function e(b){return function(a){f[b]=a;c--;c||g(f)}}var f=[],c=0;do f.push(void 0),c++,a(h.value).Ga(e(f.length-1),
b),h=d.next();while(!h.done)})};return c});P("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});P("Array.from",function(k){return k?k:function(c,d,a){I();d=d?d:function(a){return a};var n=[],l=c[Symbol.iterator];if("function"==typeof l)for(c=l.call(c);!(l=c.next()).done;)n.push(d.call(a,l.value));else{l=c.length;for(var m=0;m<l;m++)n.push(d.call(a,c[m]))}return n}});
P("Object.assign",function(k){return k?k:function(c,d){for(var a=1;a<arguments.length;a++){var n=arguments[a];if(n)for(var l in n)Object.prototype.hasOwnProperty.call(n,l)&&(c[l]=n[l])}return c}});P("Array.prototype.find",function(k){return k?k:function(c,d){a:{var a=this;a instanceof String&&(a=String(a));for(var n=a.length,l=0;l<n;l++){var m=a[l];if(c.call(d,m,l,a)){c=m;break a}}c=void 0}return c}});P("Object.is",function(k){return k?k:function(c,d){return c===d?0!==c||1/c===1/d:c!==c&&d!==d}});
P("Array.prototype.includes",function(k){return k?k:function(c,d){var a=this;a instanceof String&&(a=String(a));var n=a.length;for(d=d||0;d<n;d++)if(a[d]==c||Object.is(a[d],c))return!0;return!1}});
P("String.prototype.includes",function(k){return k?k:function(c,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(c,d||0)}});
(function(k){function c(a){if(d[a])return d[a].wa;var n=d[a]={ld:a,yc:!1,wa:{}};k[a].call(n.wa,n,n.wa,c);n.yc=!0;return n.wa}var d={};c.K=k;c.G=d;c.C=function(a,d){c.D(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:d})};c.M=function(a){var d=a&&a.Pc?function(){return a["default"]}:function(){return a};c.C(d,d);return d};c.D=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};c.N="";return c(c.V=8)})([function(k,c,d){k=d(10);d=window;Object(k.a)(d);c.a=d},function(k,
c,d){function a(b){var a=!1;return function(e){for(var f=[],G=0;G<arguments.length;++G)f[G-0]=arguments[G];if(!a){a=!0;try{b.apply(b,f)}catch(y){}}}}function n(b){b=void 0===b?[]:b;if(!Array.isArray(b))return[];b=Array.from(b);for(var a=b.length;a;a--){var e=Math.floor(Math.random()*a),f=M([b[e],b[a-1]]);b[a-1]=f.next().value;b[e]=f.next().value}return b}function l(b,a){a=void 0===a?q().location:a;a=decodeURI(a);b=b.replace(/[\[\]]/g,"\\$&");return(b=(new RegExp("[?&]"+b+"(=([^&#]*)|&|#|$)")).exec(a))?
b[2]?decodeURIComponent(b[2].replace(/\+/g," ")):"":null}function m(b){return parseInt(b,10)}function p(b,a){var e;if(a&&"string"===typeof a){if(-1!==a.indexOf(".")){a=a.split(".");for(var f=!1,g=0;g<a.length;g++){if("object"!==typeof b){f=!0;break}b=p(b,a[g])}f||(e=b);return e}f="get"+a[0].toUpperCase()+a.slice(1);a=b&&"function"===typeof b[f]?f:a;b&&(b.hasOwnProperty(a)||"function"===typeof b[a])&&(e="function"===typeof b[a]?b[a]():b[a]);return e}}function h(b){return b?'<script type="text/javascript" src="'+
b+'">\x3c/script>':""}function g(b,a){if(!b)return"";a=a.split("x");return'<iframe id="'+r()+'" width="'+a[0]+'" '+('height="'+a[1]+'" marginwidth="0" marginheight="0" ')+('style="border:0" frameborder="0" src="'+b+'" border="0" ')+'scrolling="no" vspace="0" hspace="0"></iframe>'}function b(b){return b?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+b+'"></div>'):""}function e(b,a){var e=[];b.forEach(function(b){-1!==a.indexOf(b)&&e.push(b)});return e}function f(){return[u.a.innerWidth||
u.a.document.documentElement.clientWidth||u.a.document.body.clientWidth,u.a.innerHeight||u.a.document.documentElement.clientHeight||u.a.document.body.clientHeight]}function v(b,a){b=Math.round(b);for(var e=0;e<a.length;e++){var f="lt"in a[e]&&b<a[e].lt||!("lt"in a[e]);!("ge"in a[e]&&b>=a[e].ge)&&"ge"in a[e]||!f||"percent"in a[e]&&(b*=a[e].percent)}for(e=0;e<a.length;e++)f="lt"in a[e]&&b<a[e].lt||!("lt"in a[e]),!("ge"in a[e]&&b>=a[e].ge)&&"ge"in a[e]||!f||("set"in a[e]?b=a[e].set:"round"in a[e]&&(b=
Math.floor(b)-Math.floor(b)%a[e].round));return b}function t(b,a,e){Object.keys(a).forEach(function(f){b=b.replace(e+f+e,a[f])});return b}function r(){return F()+Math.random().toString(16).substr(2)}function q(b){b=void 0===b?"":b;var a=u.a.document.createElement("a");a.href=b||u.a.location;return{location:a.href,href:a.href,protocol:a.protocol,hostname:a.hostname,host:a.host,Aa:a.Aa,pathname:a.pathname,search:a.search,oa:a.oa,origin:a.origin}}function C(b){return Object.keys(b).map(function(a){return Array.isArray(b[a])?
b[a].map(function(b){return a+"[]="+b}).join("&"):a+"="+b[a]}).join("&")}c.f=C;var u=d(0),B=d(2),F=function(){var b=0;return function(){b++;return b}}();c.h=r;c.l=t;k={highestCPMWins:function(b,a){if(0===b.length)return null;for(var e={J:0},f=0;f<b.length;f++)e.J>=b[f].J?a.log("sbi",B.q,[b[f].J,b[f].X]):e=b[f];return e.J?e:null},sonobiDealWinsOverHighestCPM:function(b,a){if(0===b.length)return null;for(var e={J:0},f=0;f<b.length;f++)if(10<=b[f].ma)b[f].J>e.J&&(a.log("sbi",B.q,[e.J,e.X]),e=b[f]);else{if("sonobi"===
b[f].X&&b[f].fa){e=b[f];b.forEach(function(g){g!==e&&a.log("sbi",B.q,[b[f].J,b[f].X])});break}e.J>=b[f].J?a.log("sbi",B.q,[b[f].J,b[f].X]):e=b[f]}return e.J||e.fa?e:null},lowestDealPriorityWinsOverHighestCPM:function(b,a){if(0===b.length)return null;b.sort(function(b,a){return b.ma-a.ma});var e=b[0].ma,f=b.filter(function(b){return b.ma===e});b={J:0};f=M(f);for(var g=f.next();!g.done;g=f.next())g=g.value,b.J>=g.J?a.log("sbi",B.q,[g.J,g.X]):b=g;return b.J||b.fa?b:null}};c.a=k;c.b=v;c.i=f;c.e=e;c.j=
p;c.g=l;c.c=n;c.k=a;c.d={fd:function(b,a){return b.reduce(function(b,e){return b.then(function(b){return a(e).then(b.push.bind(b)).then(function(){return b})})},Promise.resolve([]))},S:q,cb:r,jd:function(b){if(b){try{var a=b.contentWindow?b.contentWindow.document:b.rb.document?b.rb.document:b.rb}catch(A){return}return a}},hd:function(){var b=u.a.document.createElement("iframe");b.id=r();b.height=0;b.width=0;b.hspace="0";b.vspace="0";b.marginWidth="0";b.marginHeight="0";b.style.border="0";b.frameBorder=
"0";b.border="0px";b.scrolling="no";b.src="about:blank";b.style.display="none";return b},vd:t,qd:function(b,a){for(var e=0,f=b.length>a.length?a.length:b.length,g=b.length<a.length?a.length:b.length,c=0;c<f;c++)b[c]===a[c]&&e++;return e/g},Oc:k,Qc:v,kd:f,cd:e,lc:C,Bb:function(b){try{var a=new RegExp(b,"i"),e=u.a.performance.getEntriesByType("resource").filter(function(b){return a.test(b.name)});return Array.isArray(e)?Math.max(e[e.length-1].$c||0,0):null}catch(D){return null}},eb:function(b){return void 0!==
{sizes:1,timeout:1}[b]},Ia:function(b){var a=u.a.innerWidth,e=null,f;for(f in b)if(b.hasOwnProperty(f)){var g=b[f].viewport.lt||Number.MAX_SAFE_INTEGER;if(a>=(b[f].viewport.ge||0)&&a<g){e=f;break}}return e},tc:function(b,a){return b.reduce(function(b,e){(b[e[a]]=b[e[a]]||[]).push(e);return b},{})},Yc:b,Wc:g,Xc:h,tb:function(a,e,f){switch(void 0===e?"SCRIPT":e){case "SCRIPT":return h(a);case "IFRAME":return g(a,void 0===f?"1x1":f);case "TRACK":return b(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+
a+"\x3c/script>":"";default:return""}},Q:p,Vc:function(b){var a=/^\d{1,4}x\d{1,4}$/;return"string"===typeof b&&a.test(b)?b.split("x").map(m):b},Cc:function(b,a){var e={},f;for(f in b)-1===a.indexOf(f)&&(e[f]=b[f]);return e},db:function(b){try{return"string"!==typeof b?void 0:u.a.document.cookie.split("; ").reduce(function(b,a){var e=M(a.split("="));a=e.next().value;e=N(e);b[a]=e.join("=");return b},{})[b]}catch(S){}},pc:l,Rc:n,Ic:function(b){void 0!==u.a.performance&&"function"===typeof u.a.performance.setResourceTimingBufferSize&&
u.a.performance.setResourceTimingBufferSize(b)},ca:a,vc:function(b,a){b=void 0===b?[]:b;a=void 0===a?[]:a;return b.reduce(function(b,e){-1===b.indexOf(e)&&-1<a.indexOf(e)&&b.push(e);return b},[])},xb:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var a=16*Math.random()|0;return("x"===b?a:a&3|8).toString(16)})},xc:function(b,a){var e={},f;for(f in b)-1!==a.indexOf(f)&&(e[f]=b[f]);return e}}},function(k,c){c.x=200001;c.n=200003;c.A=200005;c.w=200006;c.d=200008;c.m=
200009;c.e=200011;c.k=200012;c.q=200017;c.B=200019;c.o=200020;c.f=200022;c.c=200023;c.b=200024;c.a=200025;c.g=200026;c.y=200027;c.z=200028;c.s=200029;c.i=200030;c.h=200031;c.v=200032;c.t=200033;c.l=200034;c.j=200035;c.p=200036;c.r=200039;c.u=200040},function(k,c,d){function a(a){return a?a.replace(/^\?/,"").split("&").reduce(function(a,b){var e=M(b.split("="));b=e.next().value;e=e.next().value;/\[\]$/.test(b)?(b=b.replace("[]",""),a[b]=a[b]||[],a[b].push(e)):a[b]=e||"";return a},{}):{}}function n(c){var g=
m.a.document.createElement("a");g.href=decodeURIComponent(c);return{protocol:(g.protocol||"").replace(/:$/,""),hostname:g.hostname,Aa:+g.Aa,pathname:g.pathname,search:a(g.search||""),oa:(g.oa||"").replace(/^#/,""),host:g.host}}function l(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.Aa?":"+a.Aa:""))+(a.pathname||"")+(a.search?"?"+Object(p.f)(a.search||""):"")+(a.oa?"#"+a.oa:"")}var m=d(0),p=d(1);c.a={lb:3E4,fb:function(a,g,b,e){var f=this;b=void 0===b?"sbi_"+Object(p.h)():b;e=void 0===
e?{}:e;a=a.replace("%%callback%%",b);return new Promise(function(c){var l=m.a.setTimeout(c,f.lb,e),v,d=Object(p.k)(function(b){m.a.clearTimeout(v);m.a.clearTimeout(l);if(null==g)c(b);else{var a={};a[g]=b;c(a)}});m.a[b]=d;f.Za("script",{src:a}).then(function(){v=m.a.setTimeout(function(){d(e)},500)})})},dc:function(a,g,b){b=void 0===b?{}:b;return new Promise(function(e,f){function c(){4===q.readyState&&(200<=q.status&&400>q.status?e(q.responseText):f({status:q.status,statusText:q.statusText}))}var t=
b.Bc||(g?"POST":"GET"),d=m.a.XDomainRequest&&(!m.a.XMLHttpRequest||void 0===(new m.a.XMLHttpRequest).responseType);if(d){var q=new m.a.XDomainRequest;q.onload=function(){e(q.responseText)};q.onerror=function(){f("xhr on error")};q.ontimeout=function(){f("xhr timeout")};q.onprogress=function(){}}else q=new m.a.XMLHttpRequest,q.onreadystatechange=c;if("GET"===t&&g){var h=n(a);Object.assign(h.search,g);a=l(h)}q.open(t,a);d||(b.withCredentials&&(q.withCredentials=!0),b.rd&&q.setRequestHeader("X-Requested-With",
"XMLHttpRequest"),q.setRequestHeader("Content-Type",b.Uc||"text/plain"));q.send("POST"===t&&g)})},Za:function(a,g){return new Promise(function(b,e){if("image"===a)var f=Object.assign(new m.a.Image,g);else if("script"===a||" iframe"===a)f=m.a.document.createElement(a),Object.keys(g||{}).forEach(function(b){f[b]=g[b]}),m.a.document.head.appendChild(f);else{e();return}f.addEventListener?f.addEventListener("load",function(){b()}):f.readyState?f.onreadystatechange=function(){3===f.readyState&&b()}:e()})}}},
function(k,c){function d(){this.C={}}d.prototype.ga=function(a){if(a in this.C){var c=Array.from(arguments);c.shift();this.C[a].R.forEach(function(a){return a.apply(a,c)});this.C[a].ca.forEach(function(a){return a.apply(a,c)});this.C[a].ca=[]}};d.prototype.ca=function(a,c){this.C[a]=this.C[a]||{R:[],ca:[]};this.C[a].ca.push(c)};d.prototype.R=function(a,c){this.C[a]=this.C[a]||{R:[],ca:[]};this.C[a].R.push(c)};d.prototype.Fc=function(a,c){this.C[a].R=this.C[a].R.filter(function(a){return a!==c});this.C[a].ca=
this.C[a].R.filter(function(a){return a!==c})};c.a=new d;c.b=new d},function(k,c){function d(a){this.W=a.globalSettings}d.prototype.na=function(a){return a?this.W[a]:this.W};c.a=d},function(k,c,d){function a(a){this.W=a.platformSettings;this.ba=new n.a(a)}var n=d(5),l=d(1);a.prototype.xa=function(a,c){return a?(a=this.W[a],c&&(a=a[c],a=l.d.eb(c)&&!a?this.ba.na(c):a),a):this.W};c.a=a},function(k,c,d){function a(a,c,d,h,g,b,e){this.ob=n.d.cb();this.N=h;this.Ra=g;this.Va=0;this.Sa=d;this.pb=c;this.D=
"";this.Xa=a;this.M={};this.Ta="";this.G=10;this.C=-1;this.Wa=1;this.K={};this.Ua=e;this.Fa=0;this.V="display";this.hb=1;"function"===typeof b.ra&&b.ra([this])}var n=d(1);a.prototype.qb=function(){return Object.assign(Object.create(this),this)};a.prototype.mc=function(){var a=this.qb(),c={buyerid:a.Sa,buyername:a.pb,adunit_code:a.Ra,pageViewId:a.Ua,bidid:a.ob,p:a.hb,response:a.Wa,s:a.Xa||"0x0",bid:a.Va,latency:a.zc,jsLatency:a.Fa};a.fa&&"string"===typeof a.fa&&(c.dealid=a.Ta);return c};x.Object.defineProperties(a.prototype,
{id:{configurable:!0,enumerable:!0,get:function(){return this.ob}},ha:{configurable:!0,enumerable:!0,get:function(){return this.Ua},set:function(a){this.Ua=a}},I:{configurable:!0,enumerable:!0,get:function(){return this.N},set:function(a){this.N=a}},mb:{configurable:!0,enumerable:!0,get:function(){return this.V},set:function(a){this.V=a}},cc:{configurable:!0,enumerable:!0,get:function(){return this.Ra},set:function(a){this.Ra=a}},J:{configurable:!0,enumerable:!0,get:function(){return this.Va},set:function(a){this.Va=
a}},X:{configurable:!0,enumerable:!0,get:function(){return this.pb}},gb:{configurable:!0,enumerable:!0,get:function(){return this.M},set:function(a){this.M=a}},zc:{configurable:!0,enumerable:!0,get:function(){return 0>=this.Na||!this.Na?-1:this.Na},set:function(a){this.Fa=Math.round(a)}},Gb:{configurable:!0,enumerable:!0,get:function(){return 0>=this.C||!this.C?-1:Math.round(this.C)},set:function(a){this.C=Math.round(a)}},Na:{configurable:!0,enumerable:!0,get:function(){return Math.round(this.Fa)},
set:function(a){this.Fa=Math.round(a)}},size:{configurable:!0,enumerable:!0,get:function(){return this.Xa},set:function(a){this.Xa=Array.isArray(a)?a.join("x"):a}},ja:{configurable:!0,enumerable:!0,get:function(){return this.Sa},set:function(a){this.Sa=a}},la:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}},fa:{configurable:!0,enumerable:!0,get:function(){return this.Ta},set:function(a){this.Ta=a}},ma:{configurable:!0,enumerable:!0,get:function(){return this.G},
set:function(a){this.G=a}},Hc:{configurable:!0,enumerable:!0,get:function(){return this.Wa},set:function(a){this.Wa=a}},$a:{configurable:!0,enumerable:!0,get:function(){return this.K},set:function(a){this.K=a}}});c.a=a},function(k,c,d){k.wa=d(9)},function(k,c,d){function a(a){if(!a.hasOwnProperty("sbi_km")||!a.sbi_km.apiReady){e.d.Ic(500);var c=a.sbi_morpheus=Object(b.a)(),d=a.sbi_km=Object.assign({API:{},config:f.a,apiReady:!1,id:e.d.cb()},a.sbi_km),t=new h.a(d.config),u=new n.a(d.config),k=new p.a(u,
t),F=new m.a(u,k,t);F.uc(d.config);d.API=Object.assign(d.API,{debug:u.hc.bind(u),getLog:u.Ab.bind(u)});(new v.a).Ec();u=new l.a(u,d.config,F,k);t=Object(g.a)(F,d.config,t.ba.na("timeout"),u,t,k);u.Mc(t.Gc);-1===a.location.search.indexOf("sbi_test")?a.document.cookie="sbi_debug=false":-1!==a.document.cookie.indexOf("sbi_debug=true")?d.API.debug(!0):-1!==a.location.search.indexOf("sbi_test")&&(a.document.cookie="sbi_debug=true",d.API.debug(!0));c.initialize();a.sbi_km.apiReady=!0;a.sbi_km.version="3.22.3"}}
Object.defineProperty(c,"__esModule",{value:!0});k=d(0);var n=d(11),l=d(12),m=d(14),p=d(23),h=d(24),g=d(26),b=d(27),e=d(1),f=d(28),v=d(29);c.main=a;a(k.a)},function(k,c){c.a=function(c){(function(a){"performance"in a||(a.performance={});Date.now=Date.now||function(){return(new Date).getTime()};if(!("now"in a.performance)){var c=Date.now();a.performance.timing&&a.performance.timing.navigationStart?c=a.performance.timing.navigationStart:a.performance.timing={navigationStart:Date.now()};a.performance.now=
function(){return Date.now()-c}}})(c);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:function(a){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");for(var c=Object(a),d=1;d<arguments.length;d++){var m=arguments[d];if(void 0!==m&&null!==m)for(var p=Object.keys(Object(m)),h=0,g=p.length;h<g;h++){var b=p[h],e=Object.getOwnPropertyDescriptor(m,b);e&&e.enumerable&&(c[b]=m[b])}}return c}})}},function(k,c,d){function a(a,
c){this.caller=c=void 0===c?l.a:c;this.ka=a;this.C=!1;this.navigationStart=n.a.performance.timing.navigationStart}var n=d(0),l=d(3),m=[];a.prototype.log=function(a,c,g,b){null!=b?b-=this.navigationStart:b=0+n.a.performance.now();a={dateTime:b,time:b-0,id:c,service:a};a.Mb=g||[];m.push(a);this.C&&"logData"in n.a.sbi_km&&(g=n.a.sbi_km.logData,this.D(g[a.id].service,a.kb,g[a.id].template,a.Mb))};a.prototype.Ab=function(){m.sort(function(a,c){return a.kb-c.kb});return m};a.prototype.G=function(a,c){for(var g=
[],b=1;b<arguments.length;++b)g[b-1]=arguments[b];n.a.console.log.apply(n.a.console,[].concat(["sonobi",a],O(g)))};a.prototype.D=function(a,c,g,b){var e=[a,c];a=g.apply(g,b);Array.isArray(a)?a.forEach(function(a){return e.push(a)}):e.push(a);n.a.console.log.apply(n.a.console,e)};a.prototype.hc=function(){var a=this;this.C=!0;this.caller.Za("script",{src:this.ka.url+"/morpheus_console.js"}).then(function(){var c=n.a.sbi_km.logData;a.Ab().forEach(function(g){a.D(c[g.id].service,g.kb,c[g.id].template,
g.Mb)})}).catch(function(c){a.G((new Date).toLocaleString(),"error in debug output",c)})};c.a=a},function(k,c,d){function a(a,e,f,c){var b=this;this.F=a;this.ka=e;this.C={};this.va=f;this.Z=c;this.D=new p.a(this.F,this);l.a.sbi_km.API.render=this.Jb=function(){var a=arguments,e=Date.now(),c=Object.assign({},f.ea),g=c[Object.keys(c).find(function(b){b=c[b];return b.id===a[1]&&!b.Ba})];if(!g)return Promise.reject("Could not find winning bid");var d=b.C[g.I];if(!d)return Promise.reject("Could not find a slot for the winning bid");
d.Kb[g.id]=e;return b.D.Jb(d,arguments[0],g.la,arguments[2],arguments[3],g.size).then(function(a){var e=Object.keys(a.Kb);e=b.va.ea[e[0]];b.F.log("sbi",h.B,[e.J,e.X]);e.Ba=!0;g.hb=3;b.Z.ra([e]);a.Sb={}}).catch(function(a){b.F.log("sbi",h.u,[a])})};g.a.ca("initialized",function(a,e){b.F.log("sbi",h.n,[a]);b.G(a);"function"===typeof e&&e();g.a.R("slotsDefined",function(a){b.F.log("sbi",h.y,[a]);b.G(a)})});g.a.R("slotsDestroyed",function(a){a.forEach(function(a){var e=b.D.Ja(a);a=b.D.Db(a);for(var f in b.C)b.C[f].P===
e&&b.C[f].I===a&&(b.C[f].ya=!0,b.F.log("sbi",h.z,[b.C[f]]))},this)});g.a.R("getSlots",function(a,e){"object"!==typeof a?e(b.C):(a.ya=!1,e(Object.keys(b.C).reduce(function(e,f){var c=b.C[f],g;for(g in a)if(c[g]!==a[g])return e;e[f]=c;return e},{})))});g.a.R("findSlot",function(a,e){"object"!==typeof a?e({}):(a.ya=!1,e(b.C[Object.keys(b.C).find(function(e){e=b.C[e];for(var f in a)if(e[f]!==a[f])return!1;return!0})]))});g.a.R("slotsRequestingRender",function(a){var e=b.M(a.U);b.K(e,a.done)});g.a.R("newPageViewRequested",
function(){b.D.Nc()});g.a.R("log",function(a){b.F.log.apply(b.F,Array.isArray(a)?a:[a])})}function n(a){a=void 0===a?this:a;if(-1<a.P.indexOf(" ")||1>a.T.length)return!1;var b=/^([a-zA-Z0-9\/_.*\\!<:()-]+)$/;return a.I&&b.test(a.I)?!0:!1}var l=d(0),m=d(1),p=d(13),h=d(2),g=d(4);a.prototype.rc=function(){var a={ab:!1},e=this;if("object"!==typeof a)return this.C;a.ya=!1;return Object.keys(this.C).reduce(function(b,c){var f=e.C[c],g;for(g in a)if(f[g]!==a[g])return b;b[c]=f;return b},{})};a.prototype.kc=
function(a){var b=this;if("object"===typeof a)return a.ya=!1,this.C[Object.keys(this.C).find(function(e){e=b.C[e];for(var f in a)if(e[f]!==a[f])return!1;return!0})]};a.prototype.K=function(){};a.prototype.Mc=function(a){this.K=a};a.prototype.M=function(a){var b={};a=M(a);for(var f=a.next();!f.done;f=a.next()){f=this.D.Ja(f.value);var c=null,g;for(g in this.C)if(this.C[g].P===f){c=this.C[g].id;break}null!=c&&(b[c]=this.C[c])}return b};a.prototype.G=function(a){var b=this,f={},c={};a.forEach(function(a){var e=
b.D.Ja(a),g=b.D.Db(a);if(!(e in c)){f[g]=f[g]++||1;var d=Object(m.h)();c[d]={I:g,xd:g+":"+f[g],P:e,id:d,wd:!1,pd:!1,ya:!1,Kb:{},ea:[],Sb:{},T:b.D.yb(a),jb:{},od:b.D.oc(a),La:b.D.yb.bind(b.D,a),ab:!1,ub:!1,Sc:0,wc:n}}});this.C=Object.assign(this.C,c)};a.prototype.Kc=function(a){for(var b in a)if(b in this.C){var f=this.C[b].P;this.C[b].Sb=a[b];this.C[b].jb=a[b].targeting;var c=Object.assign({},this.va.ea)[a[b].id];c&&(c.la=a[b].creative,c.size=a[b].size,c.jb=a[b].targeting,this.C[b].jb.sbi_size=a[b].size,
this.D.Jc(f,a[b].targeting))}};x.Object.defineProperties(a.prototype,{U:{configurable:!0,enumerable:!0,get:function(){return this.C},set:function(a){this.C=a}}});c.a=a},function(k,c,d){function a(a,b){var e=this;this.G=!1;this.K=this.Da=Function;this.Ea={};this.C={};this.F=a;this.M=[];this.ta=b;l.a.googletag=l.a.googletag||{};l.a.googletag.cmd=l.a.googletag.cmd||[];if(l.a.googletag.pubadsReady)a.log("sbi",h.r);else{a=this.Vb();var f=!1;l.a.googletag.cmd[a](function(){f||(f=!0,e.Ea=l.a.googletag,e.C=
e.Ea.pubads(),e.Zb(),e.Yb())});!1!==Object(p.j)(b.ka,"globalSettings.osEnabled")&&n(a,l.a.googletag.cmd);this.N={md:!1,Ya:!1,vb:!1};this.V={}}}function n(a,b){b=void 0===b?l.a.googletag.cmd:b;if("u"===a[0]){var e=b.splice;b[a]=function(a){e.apply(b,[1,0,a]);return this.length};b.splice=function(){var a=b.shift();e.apply(b,arguments);return e.apply(b,[0,0,a])}}}var l=d(0),m=d(4),p=d(1),h=d(2);a.prototype.Vb=function(){return null!=l.a.googletag.cmd.length?"unshift":"push"};a.prototype.ac=function(a,
b,e){e?a.postMessage({creative:b,message:"SBI_RENDER"},e):a.document.write(b)};a.prototype.bc=function(a,b,e,f,c,d,m){f=f.split("x");var g=parseInt(f[0],10),v=parseInt(f[1],10);if(this.Ub(a,g,v))if(d)a=l.a.document.getElementById(b).getElementsByTagName("div"),a=Array.from(a).filter(function(a){return-1<a.id.indexOf("google_ads_iframe")}),a.forEach(function(a){var b=a.childNodes[0];b.width=g;b.height=v;a.style.width=g+"px";a.style.height=v+"px";e.postMessage({creative:c,message:"SBI_RENDER"},d)});
else{if(e.inDapIF)try{l.a.document.getElementsByName(e.frameElement.name)[0].width=g,l.a.document.getElementsByName(e.frameElement.name)[0].height=v}catch(u){this.F.log("sbi",h.k)}e.document.write(c)}else m(a)};a.prototype.$b=function(a){var b=this;return function(e){var f=b.D(a.P);b.ha(f);b.K.apply(b.C,[[f],{changeCorrelator:!1}]);throw e;}};a.prototype.Jb=function(a,b,e,f,c,d){var g=this,v=this;return(new Promise(function(t,m){v.F.log("sbi",h.v,[a]);a.rendering=!0;var q=e;f&&Object.keys(f).forEach(function(a){Array.isArray(f[a])||
(f[a]=[f[a]]);q=q.replace("%%"+a+"%%",f[a].join(","))});if(g.ta.ka.globalSettings.supportResizing){var l=g.D(a.P);g.bc(l,a.P,b,d,q,c,m)}else g.ac(b,q,c);v.F.log("sbi",h.t,[a]);t(a)})).catch(this.$b(a))};a.prototype.ha=function(a){var b=a.getTargetingMap();b=Object.keys(b).filter(function(a){return"sbi"===a.substr(0,3)});0<b.length&&b.forEach(function(b){a.clearTargeting(b)})};a.prototype.D=function(a){var b=this;return this.sa().find(function(e){return b.Ja(e)===a})||null};a.prototype.Ja=function(a){return a&&
"getSlotElementId"in a?a.getSlotElementId():null};a.prototype.sa=function(){return this.C.getSlots()};a.prototype.Db=function(a){return a.getAdUnitPath()};a.prototype.Ub=function(a,b,e){var f=!1;this.La(a).forEach(function(a){f=f||a.Rb===b&&a.Eb===e});return f};a.prototype.yb=function(a){return this.La(a).map(function(a){return a.Rb+"x"+a.Eb})};a.prototype.La=function(a){a=a.getSizes.apply(a,Object(p.i)());a=Array.isArray(a)?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{Rb:a.getWidth(),
Eb:a.getHeight()}})};a.prototype.Jc=function(a,b){if(a=this.D(a))for(var e in b)e&&b[e]&&a.setTargeting(e,b[e])};a.prototype.Nc=function(){this.C.updateCorrelator()};a.prototype.Zb=function(){var a=this,b=l.a.googletag.enableServices;l.a.googletag.enableServices=function(){var e=this,f=arguments;a.F.log("sbi",h.h);a.G||(a.G=!0,m.a.ga("initialized",a.sa(),function(){b.apply(e,f);a.F.log("sbi",h.l,[a.M.toString()]);a.M.forEach(function(a){return l.a.googletag.display(a)});a.M=[]}))};var e=this.C.enableSingleRequest;
this.C.enableSingleRequest=function(){a.G||(a.N.vb=!0);e.apply(this,arguments)};var f=this.C.disableInitialLoad;this.C.disableInitialLoad();a.Ya=f;this.C.disableInitialLoad=function(){a.Wb||(a.N.Ya=!0);f.apply(this,arguments)}};a.prototype.Yb=function(){function a(a){if(a&&Object.keys(a).length){var b=Object(p.h)();e.V[b]={};for(var c in a)a[c].ab=!0;e.V[b]=a;c=Object.keys(a).map(function(b){return e.D(a[b].P)});for(var g=M(c),d=g.next();!d.done;d=g.next())e.ha(d.value);var v={U:c,done:function(){var a=
f.V[b],e=Object.keys(a).map(function(b){return f.D(a[b].P)});f.F.log("sbi",h.s,[v.U]);f.K.apply(f.C,[e,{changeCorrelator:!1}])}};m.a.ga("slotsRequestingRender",v)}}function b(a){e.Da.apply(l.a.googletag,a)}var e=this,f=this,c=l.a.googletag.defineSlot;l.a.googletag.defineSlot=l.a.googletag.defineUnit=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var a=c.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?
"/":"")+a};f.G&&m.a.ga("slotsDefined",[a])}return a};var d=l.a.googletag.defineOutOfPageSlot;l.a.googletag.defineOutOfPageSlot=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var a=d.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};a.isOutOfPage=!0;f.G&&m.a.ga("slotsDefined",[a])}return a};var k=l.a.googletag.destroySlots;l.a.googletag.destroySlots=function(){var a=k.apply(this,arguments);if(a){var b=
arguments.length?arguments[0].filter(function(a){return f.Xb(a)}):f.C.getSlots();m.a.ga("slotsDestroyed",b)}return a};this.K=this.C.refresh;this.C.refresh=function(){var a=Array.from(arguments),b={};0<a.length&&Array.isArray(a[0])?0===a[0].length?b.U=[]:(b.U=[],a[0].forEach(function(a){a&&"object"===typeof a&&"function"===typeof a.getSizes?b.U.push(a):f.F.log("sbi",h.p,[a])})):b.U=f.sa();b.done=function(){f.F.log("sbi",h.s,[b.U]);f.K.apply(f.C,a)};b.U.forEach(function(a){f.ha(a)});m.a.ga("slotsRequestingRender",
b)};this.Da=l.a.googletag.display;l.a.googletag.display=function(f){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];e.Wb=!0;d=0<c.length&&("string"===typeof c[0]||"object"===typeof c[0]);var g=c[0];"object"===typeof g&&(g=g.id);g=e.ta.kc({P:g||""});var v=e.ta.rc(),m=!!g,l=e.N.Ya,t=e.N.vb,k=m&&!0===g.ub;e.G?m&&d?k||(g.ub=!0,b(c),l||(t?a(v):(c=g,c.ab=!0,e.F.log("sbi",h.i,[c]),c=e.D(c.P),e.C.refresh([c],{changeCorrelator:!1})))):b(c):(e.F.log("sbi",h.j,[c[0]]),e.M.push(c[0]))}};a.prototype.oc=
function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};a.prototype.Xb=function(a){try{return"function"===typeof a.gd}catch(b){return!1}};c.a=a},function(k,c,d){function a(a,e,c){this.F=a;this.D={};this.Z=e;this.C={};this.K=c;this.G={}}var n=d(1),l=d(15),m=d(0),p=d(2),h=d(16),g=d(17);a.prototype.uc=function(a){var b=this;a.adapterSettings.map(function(e){var c=e.name;e=new l.a(a,c);var f=g.a[c];e.ic&&(b.C[c]={ia:f,O:e},b.F.log("sbi",p.e,[c]),b.C[c].Lc=f.Ca(e,b.Z,b.F).then(function(a){b.F.log("sbi",
p.f,[c]);return a}))})};a.prototype.N=function(a){var b={};Object.keys(a).forEach(function(e){a[e].forEach(function(a){b[a.id]=a})});this.D=Object.assign(this.D,b);return b};a.prototype.Nb=function(a,e,c,d){var b=this;this.F.log("sbi",p.x,[e]);this.F.log("sbi",p.w);var f=Object.keys(this.C).map(function(a){return{va:b.C[a],Qa:!1}});this.G[c]=new h.a(c,f,a,e,this.F,this.Z);this.G[c].Ca(function(a){d(b.N(a))})};a.prototype.M=function(a,e){var b=this,c=a.reduce(function(a,b){a[b.X]=a[b.X]||[];a[b.X].push(b);
return a},{});return Object.keys(c).reduce(function(a,f){var d=n.a.sonobiDealWinsOverHighestCPM(c[f],b.F);d&&(a["sbi_"+f+"_price"]=Object(n.b)(d.J,e),a["sbi_"+f+"_size"]=d.size);return a},{})};a.prototype.sc=function(a,e,c){if(0===a.length)return{};var b={};a.forEach(function(a){b[a.I]=b[a.I]||[];b[a.I]=b[a.I].concat(a)});a={};for(var f=M(Object.keys(b)),d=f.next();!d.done;d=f.next())if(d=d.value,0!==b[d].length){var g=n.a.sonobiDealWinsOverHighestCPM(b[d],this.F);if(null!=g){g.nb=!0;a[d]={targeting:{}};
a[d].id=g.id;this.K.ba.na().widgetRender&&(a[d].targeting.sbi_lookup_id=m.a.sbi_km.id);a[d].targeting.sbi_kmid=g.id;a[d].targeting.sbi_bidder=g.X;a[d].targeting.sbi_ct=g.mb;var h=Object(n.b)(g.J,e);"number"===typeof h&&0<h&&(a[d].targeting.sbi_price=h);for(var l in g.$a)a[d].targeting[l]=g.$a[l];h=g.la;h=Object(n.l)(h,g.gb,"%%");a[d].creative=h;a[d].size=g.size;c&&(a[d].targeting=Object.assign(a[d].targeting,this.M(b[d],e)))}}this.F.log("sbi",p.A,[a]);return a};x.Object.defineProperties(a.prototype,
{ea:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}}});c.a=a},function(k,c,d){function a(a,e){if(!e)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.W=a.adapterSettings;this.da=new h.a(a);a=this.W;for(var b={},c=0;c<a.length;c++)b[a[c].name]=a[c];this.G=b;this.H=e;this.D=this.G[e];this.V=n;this.N=l}function n(a,e,c){a=g.d.Q(a,void 0===c?"dimensions.platforms":c)||[];return"*"===e||0===a.length||-1<a.indexOf("*")?
!0:-1<a.indexOf(e)}function l(a,e){e=void 0===e?"dimensions.domains":e;var b=g.d.S().location;a=g.d.Q(a,e)||[];if(0===a.length||-1<a.indexOf("*"))return!0;if("string"===typeof a)return(new RegExp(a)).test(b);for(e=0;e<a.length;e++)if((new RegExp(a[e])).test(b))return!0;return!1}function m(a,e){for(var b=[],c=0;c<e.length;c++)for(var d=g.d.Q(e[c],"dimensions.domIds")||[],h=0;h<d.length;h++)if(d[h]===a){b.push(e[c]);break}return b}function p(a,e){for(var b=a;0<=b.lastIndexOf("/")&&"/"!==b;){if((g.d.Q(e,
"dimensions.adUnits")||[]).some(function(a){return a.toLowerCase()===b.toLowerCase()}))return!0;b=b.substr(0,b.lastIndexOf("/"))}return!1}var h=d(6),g=d(1);a.prototype.bb=function(a){var b=a.za;a=this.G[void 0===a.H?this.H:a.H];b&&(a=a[b],a=g.d.eb(b)&&!a?this.da.xa(g.d.Ia(this.da.xa()),b):a);return a};a.prototype.Ka=function(a){var b=a.name;return this.C({H:void 0===a.H?this.H:a.H,L:void 0===a.L?"requestSettings":a.L}).find(function(a){return a.name===b})};a.prototype.qc=function(){var a={name:"targeting"},
c=a.name;return this.C({H:void 0===a.H?this.H:a.H,L:void 0===a.L?"requestSettings":a.L}).reduce(function(a,b){b.name===c&&a.push(b);return a},[])};a.prototype.Cb=function(){return(this.aa({name:"protocol"})||"https").replace(":","").replace("//","")};a.prototype.aa=function(a){return(a=this.Ka({name:a.name,L:void 0===a.L?"requestSettings":a.L,H:void 0===a.H?this.H:a.H}))?a.value:void 0};a.prototype.C=function(a){var b=[];a=this.G[void 0===a.H?this.H:a.H][void 0===a.L?"requestSettings":a.L]||[];for(var c=
0;c<a.length;c++){var d=a[c];if(d.hasOwnProperty("dimensions")){var h="*";this.da.W&&(h=g.d.Ia(this.da.xa()));l(d)&&n(d,h)&&b.push(d)}else b.push(d)}return b};a.prototype.Fb=function(a){var b=a.I,c=void 0===a.Y?"placementid":a.Y;a=this.C({H:void 0===a.H?this.H:a.H,L:void 0===a.L?"requestSettings":a.L});for(var d=b;0<=d.lastIndexOf("/")&&"/"!==d;){b=a.filter(function(a){return a.name.toLowerCase()===c.toLowerCase()});b=M(b);for(var h=b.next();!h.done;h=b.next())if(h=h.value,(g.d.Q(h,"dimensions.adUnits")||
[]).some(function(a){return a.toLowerCase()===d.toLowerCase()}))return[h];d=d.substr(0,d.lastIndexOf("/"))}return[]};a.prototype.K=function(a){var b=a.I,c=void 0===a.Y?"placementid":a.Y;a=this.C({H:void 0===a.H?this.H:a.H,L:void 0===a.L?"requestSettings":a.L}).filter(function(a){return a.name.toLowerCase()===c.toLowerCase()});return(a=m(b.P,a).filter(function(a){return g.d.Q(a,"dimensions.adUnits.length")?p(b.I,a):!0}).filter(function(a){return g.d.Q(a,"dimensions.sizes.length")?a.dimensions.sizes.some(function(a){return-1!==
b.T.indexOf(a)}):!0})[0])?[a]:[]};a.prototype.M=function(a){var b=void 0===a.T?[]:a.T,c=void 0===a.Y?"placementid":a.Y;return this.C({H:void 0===a.H?this.H:a.H,L:void 0===a.L?"requestSettings":a.L}).filter(function(a){return a.name.toLowerCase()===c.toLowerCase()}).filter(function(a){return(g.d.Q(a,"dimensions.sizes")||[]).some(function(a){return-1!==b.indexOf(a)})})};a.prototype.Ac=function(a){var b=this,c=void 0===a?{}:a;a=void 0===c.U?[]:c.U;var d=void 0===c.L?"requestSettings":c.L,h=void 0===
c.H?this.H:c.H,m=void 0===c.Y?"placementid":c.Y;c=a;Array.isArray(a)||(c=[c]);return c.map(function(a){var c=b.K({I:a,L:d,H:h,Y:m});if(c.length)return c;c=b.Fb({I:a.I,L:d,H:h,Y:m}).filter(function(a){return!g.d.Q(a,"dimensions.domIds.length")}).filter(function(b){return b.dimensions.sizes&&0!==b.dimensions.sizes.length?b.dimensions.sizes.some(function(b){return-1!==a.T.indexOf(b)}):!0});return c.length?c:b.M({T:a.T,L:d,H:h,Y:m}).filter(function(a){return!g.d.Q(a,"dimensions.adUnits.length")}).filter(function(a){return!g.d.Q(a,
"dimensions.domIds.length")})})};x.Object.defineProperties(a.prototype,{ic:{configurable:!0,enumerable:!0,get:function(){var a="false"===g.d.pc("sbi_"+this.H)?!1:!0,c="*";this.da.W&&(c=g.d.Ia(this.da.xa()));var f=1;"number"===typeof this.D.frequency&&(f=this.D.frequency);return a&&!this.D.disabled&&this.V(this.D,c,"platforms")&&this.N(this.D,"domain")&&Math.random()<=f}}});c.a=a},function(k,c,d){function a(a,c,d,b,e,f){this.id=a;this.D=Object(n.c)(c);this.U=d;this.F=e;this.Z=f;this.ea=[];this.K=b;
this.Ma=!1;this.Ca=this.Ca.bind(this);this.C=this.C.bind(this)}var n=d(1),l=d(0),m=d(2);a.prototype.C=function(){return this.ea.reduce(function(a,c){(a[c.I]=a[c.I]||[]).push(c);return a},{})};a.prototype.G=function(c,d,g){var b=this;return function(e){for(var f=[],h=0;h<arguments.length;++h)f[h-0]=arguments[h];f.forEach(function(e){e.hb=2;d&&(e.J=Object(n.b)(e.J,d));e.Na=Math.round(l.a.performance.now()-g);e.Ba=!1;e=a.G(Object(n.g)("sbi_price_"+c.va.ia.name),e);b.Ma?(e.Ma=!0,b.Z.ra([e])):c.Qa?(e.gc=
!0,b.Z.ra([e])):b.ea.push(e)})}};a.prototype.Ca=function(c){var d=this,g=Object(n.k)(function(){c(d.C())});l.a.setTimeout(function(){d.F.log("sbi",m.m);d.Ma=!0;g()},this.K);var b=0;this.D.forEach(function(c){var e=c.va,h=e.ia.O.bb({za:"timeout"}),k=e.ia.O.bb({za:"priceRules"}),p=Object(n.k)(function(){b+=1;b>=d.D.length&&g()});l.a.setTimeout(function(){d.F.log("sbi",m.d,[e.ia.name,h]);c.Qa=!0;p()},h);var q=l.a.performance.now(),C=a.C(e.ia.O,d.U);0<Object.keys(C).length?e.Lc.then(function(){e.ia.pa(C,
d.id,d.G(c,k,q),p)}).catch(function(){p()}):p()})};c.a=a;a.D=function(a){return Object.keys(a).reduce(function(c,d){var b=a[d];b.wc()&&(c[d]=b);return c},{})};a.C=function(c,d){c=c.bb({za:"sizes"});var g={},b;for(b in d)d.hasOwnProperty(b)&&(g[b]=Object.assign({},d[b]),g[b].T=Object(n.e)(d[b].La(),c));return a.D(g)};a.G=function(a,c){a&&""!==c.la&&0<c.J&&(c.J=parseInt(a,10));return c}},function(k,c,d){k=d(18);var a=d(19);d=d(21);c.a={sonobi:new k.a(a.a),bRealTime:new k.a(d.a)}},function(k,c,d){function a(a){this.name=
a.name;this.ja=a.ja;this.qa=a.qa;this.pa=a.pa;this.parse=a.parse;this.$=a.$;this.Ha=a.Ha;this.done=Function;this.caller=n.a;this.O={};this.F={};this.D=Promise.resolve({});this.Tb=a.Tb;this.C=!1}var n=d(3),l=d(2);a.prototype.Ca=function(a,c,d){this.C||(this.F=d,this.O=a,this.C=!0,d.log("sbi",l.e,[this.name]),this.D=this.qa(a,c,d)||Promise.resolve({}));return this.D};c.a=a;a.$=function(a){return a}},function(k,c,d){function a(a){switch(a){case "href":return h.d.S().location;case "hash":return h.d.S().protocol+
h.d.S().host+h.d.S().pathname+h.d.S().oa;case "search":return h.d.S().protocol+h.d.S().host+h.d.S().pathname+h.d.S().search;case "pathname":return h.d.S().protocol+h.d.S().host+h.d.S().pathname}}function n(a){var b=["hfa","cdf","ant","gmgt"].map(function(b){return l(a,b)}).filter(function(a){return a});b.push(m(a));return b.reduce(function(a,b){var c=b.ib;b=b.exec;var e="";"function"===typeof b&&(e=b(c));if(!e)return a;if("object"===typeof e||Array.isArray(e))e=JSON.stringify(e);return a+"&"+c.name.replace("_cookie_key",
"")+"="+encodeURIComponent(e)},"")}function l(a,b){var c=a.Ka({name:b});if(c)return{ib:c,exec:function(a){return h.d.Q(g.a,a.value)}};if(c=a.Ka({name:""+b+"_cookie_key"}))return{ib:c,exec:function(a){return h.d.db(a.value)}}}function m(a){return{ib:{name:"vp"},exec:function(){return(h.d.Ia(a.da.xa())||"desktop").toLowerCase()}}}function p(a,b){b=void 0===b?"href":b;return a.aa({name:"referrer"})||h.d.S()[b]}var h=d(1),g=d(0),b=d(7),e=d(2),f=d(20);c.a={qa:function(b,c,e){this.O=b;this.Z=c;this.F=e;
this.location=a(b.aa({name:"pageViewLocation"}));this.Hb=h.d.xb();this.Dc=b.aa({name:"oracleTimeout"})||0;this.Oa=new f.a(this.Dc,b);this.Oa.jc()},pa:function(c,d,f,l){function k(){return Promise.resolve()}var m=this,q={},v={},t={slots:{}},r=a(this.O.aa({name:"pageViewLocation"}));r!==this.location&&(this.location=r,this.Hb=h.d.xb());var A=!1;for(y in c)if(null!=c[y]&&Object.keys(c[y]).length){r=c[y];var D=r.I+"|"+encodeURIComponent(r.P);A=this.O.Fb({I:c[y].I,Y:"slot_override"})||[];if(0<A.length){var J=
h.d.vc(h.d.Q(A[0],"dimensions.sizes"),r.T);if(0<J.length)A=this.Oa.zb({sbi_ad:r.I,sbi_size:J}),q[D]=J.join(",");else continue}else A=this.Oa.zb({sbi_ad:r.I,sbi_size:r.T}),q[D]=r.T.join(",");A&&(t.slots[D]=A,delete q[D]);v[D]=new b.a(r.T[0],"sonobi","sonobi",y,r.I,this.Z,d)}d=n(this.O);var y=this.O.aa({name:"testUrl1"});r=this.O.Cb();y=y||r+"://apex.go.sonobi.com/trinity.js?key_maker=";var Q=h.d.cb(),R=this.Ha(y,q,"%%callback%%",d,this.Hb,p(this.O,"hostname"));this.F.log("sbi",e.c,["sonobi",c]);d=
this.O.Ka({name:"pubid"});null!=d&&null==h.d.db("sbi_user_sync_complete")&&(k=this.caller.Za.bind(this.caller,"script",{src:"https://sync.go.sonobi.com/uc.js?pubid="+d.value}),d=new Date,d.setTime(Number(d)+12096E5),g.a.document.cookie="sbi_user_sync_complete=true; expires="+d.toUTCString()+"; path=/");this.F.log("sbi",e.c,["sonobi",c]);return k().then(function(){return Object.keys(q).length?m.caller.fb.bind(m.caller,R)():{}}).then(function(a){a.slots?Object.assign(a.slots,t.slots):(t.sbi_dc=m.Oa.Qb,
a=t);m.F.log("sbi",e.b,["sonobi",c,a]);var b=h.d.Bb(Q);a=m.parse.call(m,a,c,b,v);f.apply(null,[].concat(O(a)));l();return a})},parse:function(a,b,c,d){var f=[];if(a.slots)for(var g in b)if(null!=b[g]&&Object.keys(b[g]).length){var h=b[g],l=h.I+"|"+h.P,k=h.I+"|"+encodeURIComponent(h.P);if(l in a.slots){k=d[k];l=a.slots[l];"sbi_aid"in l||(l={sbi_aid:null,sbi_apoc:null,sbi_size:null});"sbi_dozer"in l||(l.sbi_dozer=!1);"sbi_pri"in l||(l.sbi_pri=10);"sbi_mouse"in l||(l.sbi_mouse=0,l.sbi_pri=1);k.J=100*
parseFloat(l.sbi_mouse);k.size=l.sbi_size||k.size;k.fa=l.sbi_dozer;k.mb=l.sbi_ct||k.mb;k.ma=parseInt(l.sbi_pri,10);k.Gb=c;k.gb={sbi_aid:l.sbi_aid,sbi_dc:a.sbi_dc};var m=this.O.aa({name:"testUrl2"})||"//%%sbi_dc%%apex.go.sonobi.com/sbi.js";k.la=this.$(m+"?ref="+encodeURIComponent(p(this.O))+"&aid=%%sbi_aid%%&as=null","SCRIPT");k.cc=h.I;l.sbi_dozer&&(k.$a={sbi_dozer:l.sbi_dozer});f.push(k)}}this.F.log("sbi",e.a,["sonobi",b,f]);return f},name:"sonobi",ja:"sonobi",dd:l,yd:"https://sync.go.sonobi.com/uc.js",
Zc:a,$:h.d.tb,Ha:function(a,b,c,e,d,f){return""+a+encodeURIComponent(JSON.stringify(b))+"&cv="+c+e+"&pv="+d+"&ref="+encodeURIComponent(f)}}},function(k,c,d){function a(a,c){this.C=[];this.lb=6E3*a;this.Qb="mco-1-";this.caller=n.a;this.ka=c;this.D=this.ka.aa({name:"testUrl"})}var n=d(3);a.prototype.zb=function(a){var c=this;return this.C.find(function(d,h){for(var g=0,b=Object.keys(a);g<b.length;g++)if(void 0===d[b[g]]||d[b[g]]!==a[b[g]]&&!a[b[g]].includes(d[b[g]]))return!1;c.C.splice(h,1);return!0})};
a.prototype.jc=function(){var a=this;0<this.lb&&this.D?this.caller.fb(this.D,"oracle","sbi_oracle").then(function(c){return c&&c.oracle?(a.Qb=c.oracle.sbi_dc,a.G(c.oracle)):{}}):Promise.resolve({})};a.prototype.G=function(a){var c=Object.keys(a.slots).map(function(c){var d=a.slots[c];c=c.split("|");d.sbi_ad=c[0];return d});return this.C=[].concat(O(c))};c.a=a},function(k,c,d){k=d(22);c.a={qa:k.a.qa,pa:k.a.pa,parse:k.a.parse,name:"bRealTime",ja:"84251b5d72",$:k.a.$}},function(k,c,d){function a(a){return a.reduce(function(a,
c){var b=c.za;c=c.value;if(-1<b.indexOf("_cookie_key"))return b=b.replace("_cookie_key",""),(c=m.d.db(c))?a+"&"+b+"="+c:a;-1<b.indexOf("_window_key")&&(b=b.replace("_window_key",""),c=m.d.Q(h.a,c));return c?a+"&"+b+"="+c:a},"")}function n(a,b,c,d,h,k,l){var e="http://ib.adnxs.com/jpt?";-1<a.indexOf("https")&&(e="https://secure.adnxs.com/jpt?");return""+e+m.d.lc({id:b,size:c,referrer:d,callback:h})+"&"+k+l}var l=d(7),m=d(1),p=d(2),h=d(0);c.a={qa:function(a,b,c){this.O=a;this.Z=b;this.F=c},pa:function(c,
b,e,d){var f=this,g=this,h=this.O.qc().map(function(a){return a.value}).map(function(a){var b=M(a.split("|"));a=b.next().value;b=b.next().value;return{za:a,value:b}}),k=a(h),C=this.O.Cb(),u=[],B=Object.keys(c);h=B.map(function(a){return c[a]});g.O.Ac({U:h}).forEach(function(a,d){var h=B[d],q=c[h];a=M(a);for(d=a.next();!d.done;d=a.next()){d=d.value;var r=d.dimensions.sizes,v=0<r.length?r.filter(function(a){return-1<q.T.indexOf(a)}):q.T;r={};v=M(v);for(var t=v.next();!t.done;r={Pa:r.Pa,ua:r.ua},t=v.next())r.ua=
new l.a(t.value,f.name,f.ja,q.id,q.I,f.Z,b),r.Pa=r.ua.id,t=n(C,d.value,r.ua.size,m.d.S().location,"%%callback%%",r.Pa,k),g.F.log("sbi",p.c,[f.name,c]),t=g.caller.fb(t,h).then(function(a){return function(b){g.F.log("sbi",p.b,[f.name,c,b]);var e=m.d.Bb(a.Pa);return f.parse(b,h,e,a.ua)}}(r)).then(function(a){e(a);return a}),u.push(t)}});return Promise.all(u).then(function(a){d();return a})},parse:function(a,b,c,d){for(var e in a)break;0<m.d.Q(a,e+".result.cpm")&&(a=a[e].result,d.I=b,d.J=Math.round((a.cpm||
0)/100),d.size=a.width+"x"+a.height,d.gb={},d.la=this.$(a.ad,"IFRAME",a.width+"x"+a.height));d.Gb=c;this.F.log("sbi",p.a,["appnexus",b,d]);return d},name:"appnexus",ja:"00165a05a0",$:m.d.tb,Ha:n}},function(k,c,d){function a(a,b){this.F=a;this.D=b;this.caller=n.a;this.C=[]}var n=d(3),l=d(1),m=d(2),p=d(0),h=d(4),g={1:"BidRequested",2:"BidReceived",3:"BidRendered"},b=["audienceNetwork"];a.prototype.G=function(a){var b=this;this.C.length||p.a.setTimeout(function(){b.M(b.C);b.C=[]},100);this.C.push(a)};
a.prototype.K=function(a){var b=0;a.fc&&(b|=16);a.Qa&&(b|=8);a.nb&&(b|=4);a.Ba&&(b|=2);switch(b){case 0:return 1;case 8:return 0;case 16:return 9;case 20:return 4;case 24:return 2;case 22:return 6;default:throw Error("Invalid bid status: "+b.toString(2)||"Assertion failed!");}};a.prototype.ra=function(a){a=M(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;this.F.log("sbi",m.g,[b.X,b]);var c={fc:0<b.J||b.fa,Qa:b.Ma||b.gc,nb:b.nb,Ba:b.Ba},e=void 0;try{e=this.K(c),b.Hc=e}catch(r){this.F.log(m.o,
[r.message])}this.G(b.mc())}};a.prototype.N=function(a){var c=l.d.xc(a,"buyername bid adunit_code s jsLatency bidid".split(" "));-1===b.indexOf(c.Tc)&&h.b.ga(g[a.p],c)};a.prototype.M=function(a){var b=void 0,c=this;b=void 0===b?this.D.ec.nc():b;a.forEach(function(a){return c.N(a)});if(b){var d=l.d.tc(a,"pageViewId");Object.keys(d).forEach(function(a){var e=d[a].map(function(a){return l.d.Cc(a,["pageViewId"])});a=b+"?pageviewid="+a+"&corscred=1&ver="+p.a.sbi_km.version;e=JSON.stringify(e);return c.caller.dc(a,
e,{Bc:"POST"}).catch(function(){})})}};c.a=a},function(k,c,d){var a=d(25),n=d(5),l=d(6);c.a=function(c){this.W=c;this.ec=new a.a(c);this.ba=new n.a(c);this.da=new l.a(c)}},function(k,c,d){function a(a){this.W=a.analyticsSettings;this.ba=new n.a(a)}var n=d(5),l=d(1);a.prototype.nc=function(){var a=this.W.url;l.d.eb("url")&&!a&&(a=this.ba.na("url"));return a};c.a=a},function(k,c,d){c.a=function(c,d,k,h,g,b){function e(){q=Object(a.h)();p[q]={sb:0,wb:0,Lb:[],Pb:[],Ob:[],Ib:!0};n.a.setTimeout(function(){p[q].Ob.forEach(function(a){return a()});
p[q].Ib=!1},d.globalSettings.renderQueue)}function f(a){q&&p[q].Ib||e();p[q].Ob.push(a);p[q].sb++}function l(a,b){var c=p[a].Lb.push(b)-1;return function(b){p[a].wb++;p[a].Pb[c]=b;p[a].wb===p[a].sb&&m(a)}}function m(a){p[a].Lb.forEach(function(b,c){b(p[a].Pb[c])})}var p={},q;return{Gc:function(e,m){n.a.sbi_morpheus.initialized||n.a.sbi_morpheus.initialize();if(Object.keys(e).length){var p=Object(a.h)(),r=Object(a.k)(function(a){var d=Object.keys(a).map(function(b){return a[b]});d.length?(h.Kc(c.sc(d,
g.ba.na("priceRules")||[],g.ba.na("sendAllKeys")||!1)),d=d.map(function(a){return a.qb()}),d.length&&(d=d.map(function(a){a.I=e[a.I].I;return a}),b.ra(d),m())):m()});0<d.globalSettings.renderQueue?f(function(){return c.Nb(e,k,p,l(q,r))}):c.Nb(e,k,p,r)}},nd:e,bd:f,ed:l,sd:m,ud:p,td:q}};var a=d(1),n=d(0)},function(k,c,d){var a=d(0),n=d(4);c.a=function(){var c=a.a.sbi_morpheus&&a.a.sbi_morpheus.cmd?a.a.sbi_morpheus.cmd:[],d=Object.assign(a.a.sbi_morpheus||{},{registration:{},register:function(){},enableReactiveSizes:function(){},
callOperator:function(){},initialized:!1,initialize:function(){for(;0<c.length;)try{c.shift()()}catch(p){}d.initialized=!0},cmd:function(){var c=[],d=c.push;c.push=function(g){for(var b=[],e=0;e<arguments.length;++e)b[e-0]=arguments[e];return a.a.sbi_morpheus.initialized?b.reduce(function(a,b){try{b()}catch(t){}a++;return a},0):d.apply(c,b)};return c}(),addEventListener:function(a,c){return n.b.R(a,c)},removeEventListener:function(a,c){return n.b.Fc(a,c)}});return d}},function(k,c){c.a={url:"//mtrx.go.sonobi.com",
adServer:"dfp",globalSettings:{sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),timeout:2E3,priceRules:[{ge:2E3,set:2E3},{ge:900,lt:2E3,round:5},{lt:900,round:1}]},adapterSettings:[{name:"sonobi",sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),timeout:1800,disabled:!1,platforms:["mobile","desktop","tablet"],priceRules:[],parseSettings:[],requestSettings:[{name:"pubid",
value:"eba2d35162",dimensions:{sizes:[],adUnits:[],domains:[],platforms:[]}}]},{name:"bRealTime",sizes:["300x250","300x600","320x50","728x90","970x250"],timeout:1800,disabled:!0,platforms:["mobile","tablet","desktop"],priceRules:[],parseSettings:[],requestSettings:[{name:"placementid",value:"11691351",dimensions:{sizes:["728x90","970x250"],adUnits:[],domains:["digitaltrends.com"],platforms:["desktop"]}},{name:"placementid",value:"11691354",dimensions:{sizes:["300x250","300x600"],adUnits:[],domains:["digitaltrends.com"],
platforms:["desktop"]}},{name:"placementid",value:"11691357",dimensions:{sizes:["320x50"],adUnits:[],domains:["digitaltrends.com"],platforms:["mobile","tablet"]}},{name:"placementid",value:"11691378",dimensions:{sizes:["728x90","970x250"],adUnits:[],domains:["themanual.com"],platforms:["desktop"]}},{name:"placementid",value:"11691379",dimensions:{sizes:["300x250","300x600"],adUnits:[],domains:["themanual.com"],platforms:["desktop"]}},{name:"placementid",value:"11691381",dimensions:{sizes:["320x50"],
adUnits:[],domains:["themanual.com"],platforms:["tablet","mobile"]}},{name:"placementid",value:"11691365",dimensions:{sizes:["728x90","970x250"],adUnits:[],domains:["es.digitaltrends.com"],platforms:["desktop"]}},{name:"placementid",value:"11691366",dimensions:{sizes:["300x250","300x600"],adUnits:[],domains:["es.digitaltrends.com"],platforms:["desktop"]}},{name:"placementid",value:"11691377",dimensions:{sizes:["320x50"],adUnits:[],domains:["es.digitaltrends.com"],platforms:["mobile","tablet"]}}]}],
platformSettings:{mobile:{viewport:{lt:768}},tablet:{viewport:{ge:768,lt:992}},desktop:{viewport:{ge:992}}},analyticsSettings:{url:"https://keymaker.go.sonobi.com/keymaker",timeout:2E3}}},function(k,c,d){function a(){this.D=n;this.G=l;this.C=this.C.bind(this)}function n(a){"SAFE_FRAME_RENDER"===a.data.key&&a.source&&m.a.sbi_km.API.render(a.source,a.data.id,a.data.macros,a.origin)}function l(a){"SBI_KM_LOOKUP"===a.data.key&&a.source&&a.data.id===m.a.sbi_km.id&&a.source.postMessage({key:"SBI_KM_LOOKUP_RESPONSE"},
a.origin)}var m=d(0);a.prototype.C=function(a){this.D(a);this.G(a)};a.prototype.Ec=function(){m.a.addEventListener("message",this.C,!1)};c.a=a}]);}).call(window);

//# sourceMappingURL=http://mtrx.go.sonobi.com/morpheus.digitaltrends.1658.js.map